const FORECAST_LIST_ACTIONS = {
    GET_FORECAST_SUCCESS: 'GET_FORECAST_SUCCESS',
    GET_FORECAST_ERROR: 'GET_FORECAST_ERROR',
    GET_FORECAST_LOADING: 'GET_FORECAST_LOADING'
};

const UNITS_CONVERTER = {
    SET_FORECAST_UNITS: 'SET_FORECAST_UNITS'
};

export {
    FORECAST_LIST_ACTIONS,
    UNITS_CONVERTER
}